name: Import GitLab Repository

on:
  repository_dispatch:
    types: [import-gitlab-repo-dryrun]

jobs:
  import-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Install Git
        run: sudo apt-get install git

      - name: Clone GitLab repository
        shell: pwsh
        env:
          GL_USERNAME: ${{ secrets.GL_USERNAME }}
          GL_TOKEN: ${{ secrets.GL_TOKEN }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # TODO: How do we want to compose the github url?
          # git remote add origin https://github.com/${{ github.repository_owner }}/${{ github.event.client_payload.github_repo }}.git
        run: |
          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
