name: Import GitLab Repository

on:
  repository_dispatch:
    types: [import-gitlab-repo-dryrun]

env:
  FINAL_REPO_NAME: ${{ github.event.client_payload.github_reponame }}

jobs:
  import-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Install Git
        run: sudo apt-get install git

      - name: Clone GitLab repository
        shell: pwsh
        env:
          GL_USERNAME: ${{ secrets.GL_USERNAME }}
          GL_TOKEN: ${{ secrets.GL_TOKEN }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Infer the repo name from the GitLab URL
          $REPO_NAME_W_EXT=Split-Path -Path ${{ github.event.client_payload.gitlab_url }} -Leaf
          # Remove extension
          $REPO_NAME = $REPO_NAME_W_EXT -replace "\.git$", ""
          echo Migrating: $env:FINAL_REPO_NAME
          
          function GitHubRepoExistence {
          param(
              [string]$repoUrl
          )
          try {
              $response = Invoke-WebRequest -Uri $repoUrl -Method Get -UseBasicParsing -ErrorAction Stop
              if ($response.StatusCode -eq 200) {
                  return $true
              } else {
                  return $false
              }
          } catch {
              return $false
          }
          }

          # Clone the GitLab repository
          echo ${{ github.event.client_payload.gitlab_url }}
          git clone https://${{ secrets.GL_USERNAME }}:${{ secrets.GL_TOKEN }}@${{ github.event.client_payload.gitlab_url }}
          echo $REPO_NAME " cloned locally"

          cd $REPO_NAME

          # Check if the GitHub repository exists
          $GITHUB_URL="https://github.com/${{ secrets.GH_USERNAME }}/$env:FINAL_REPO_NAME.git"
          $result = GitHubRepoExistence($GITHUB_URL)
          echo "Github repo $($GIHUB_URL) already exists result: $($result)"

          # Create the GitHub repository if it doesn't exist
          if ( !$result ){
          # For the Dry run ensure the github repo is readonly for everyone besides admins. 
          $body = @{
              name = $env:FINAL_REPO_NAME
              required_status_checks = @{
              strict = $true
              contexts = @()
              }
              enforce_admins = $true
              required_pull_request_reviews = @{
              dismissal_restrictions = @{
              users = @()
              teams = @()
              }
              dismiss_stale_reviews = $true
              require_code_owner_reviews = $true
              required_approving_review_count = 1
              }
              restrictions = @{
              users = @()
              teams = @()
              apps = @()
              }
          } | ConvertTo-Json
          echo $body
          Invoke-RestMethod -Uri "https://api.github.com/user/repos" -Method Post -Headers @{Authorization = "token ${{ secrets.GH_TOKEN }}"} -Body $body -ContentType "application/json"
          }

          # Remove the existing origin
          git remote remove origin
          # Add the new origin
          echo "Updating origin"
          git remote add origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_USERNAME }}/$env:FINAL_REPO_NAME.git
          echo "Pushing to origin"

          # Push all branches and tags to the new origin
          git push -u origin --all
          git push -u origin --tags

          # Back home
          cd ..
